package com.itsol.websmart.model;
// Generated Feb 28, 2019 10:23:30 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblCandidate generated by hbm2java
 */
@Entity
@Table(name = "tbl_candidate", catalog = "smart_web")
public class TblCandidate implements java.io.Serializable {

	private Integer candidateId;
	private TblUser tblUser;
	private TblJob tblJob;
	private String candidateFirstname;
	private String candidatelLastname;
	private Date candidateBirth;
	private String candidateEmail;
	private String candidateMobile;
	private String candidateCvfile;
	private String candiateContent;
	private Integer candidateProfileId;

	public TblCandidate() {
	}

	public TblCandidate(TblJob tblJob) {
		this.tblJob = tblJob;
	}

	public TblCandidate(TblUser tblUser, TblJob tblJob, String candidateFirstname, String candidatelLastname,
			Date candidateBirth, String candidateEmail, String candidateMobile, String candidateCvfile,
			String candiateContent, Integer candidateProfileId) {
		this.tblUser = tblUser;
		this.tblJob = tblJob;
		this.candidateFirstname = candidateFirstname;
		this.candidatelLastname = candidatelLastname;
		this.candidateBirth = candidateBirth;
		this.candidateEmail = candidateEmail;
		this.candidateMobile = candidateMobile;
		this.candidateCvfile = candidateCvfile;
		this.candiateContent = candiateContent;
		this.candidateProfileId = candidateProfileId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "candidate_id", unique = true, nullable = false)
	public Integer getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(Integer candidateId) {
		this.candidateId = candidateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_user_user_id")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_job_job_id", nullable = false)
	public TblJob getTblJob() {
		return this.tblJob;
	}

	public void setTblJob(TblJob tblJob) {
		this.tblJob = tblJob;
	}

	@Column(name = "candidate_firstname", length = 45)
	public String getCandidateFirstname() {
		return this.candidateFirstname;
	}

	public void setCandidateFirstname(String candidateFirstname) {
		this.candidateFirstname = candidateFirstname;
	}

	@Column(name = "candidatel_lastname", length = 45)
	public String getCandidatelLastname() {
		return this.candidatelLastname;
	}

	public void setCandidatelLastname(String candidatelLastname) {
		this.candidatelLastname = candidatelLastname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "candidate_birth", length = 10)
	public Date getCandidateBirth() {
		return this.candidateBirth;
	}

	public void setCandidateBirth(Date candidateBirth) {
		this.candidateBirth = candidateBirth;
	}

	@Column(name = "candidate_email", length = 45)
	public String getCandidateEmail() {
		return this.candidateEmail;
	}

	public void setCandidateEmail(String candidateEmail) {
		this.candidateEmail = candidateEmail;
	}

	@Column(name = "candidate_mobile", length = 45)
	public String getCandidateMobile() {
		return this.candidateMobile;
	}

	public void setCandidateMobile(String candidateMobile) {
		this.candidateMobile = candidateMobile;
	}

	@Column(name = "candidate_cvfile", length = 65535)
	public String getCandidateCvfile() {
		return this.candidateCvfile;
	}

	public void setCandidateCvfile(String candidateCvfile) {
		this.candidateCvfile = candidateCvfile;
	}

	@Column(name = "candiate_content", length = 65535)
	public String getCandiateContent() {
		return this.candiateContent;
	}

	public void setCandiateContent(String candiateContent) {
		this.candiateContent = candiateContent;
	}

	@Column(name = "candidate_profile_id")
	public Integer getCandidateProfileId() {
		return this.candidateProfileId;
	}

	public void setCandidateProfileId(Integer candidateProfileId) {
		this.candidateProfileId = candidateProfileId;
	}

}
